seed: 42
paths:
  raw_pcap_dir: ../pcaps
  processed_dir: ../data/processed
  models_dir: ../models
  reports_dir: ../reports
  scaler_path: ../models/feature_scaler.joblib
  supervised_model_path: ../models/supervised.pt
  manifest_path: ../data/processed/feature_manifest.json
  metrics_path: ../reports/metrics_summary.json
windowing:
  window_size: 1.0
  hop_size: 0.5
  sequence_length: 30
  sequence_stride: 30
  max_windows: 50000
feature:
  micro_bins: 8
  top_udp_ports:
  - 1900
  - 53
  - 123
  - 80
  - 443
labels:
  intervals_csv: ../data/attack_intervals.csv
  default_family: normal
  family_mapping:
    normal: 0
    ssdp: 1
    syn: 2
    icmp: 3
    udp: 4
    http: 5
    other: 6
  attack_families:
  - ssdp
  - syn
  - icmp
  - udp
  - http
  - other
data:
  train_files: []
  val_files: []
  test_files: []
  normal_families:
  - normal
training:
  supervised:
    batch_size: 16
    num_workers: 4
    max_epochs: 50
    learning_rate: 0.0005
    weight_decay: 0.01
    grad_clip: 1.0
    bce_pos_weight: 3.0
    early_stopping_patience: 6
    precision_mode: autocast
    max_train_batches: null
    max_val_batches: null
model:
  supervised:
    input_dropout: 0.1
    rnn_type: lstm
    hidden_size: 128
    num_layers: 2
    bidirectional: true
    dropout: 0.2
    attention: true
    attention_heads: 4
postprocessing:
  tau_window: 0.2
  tau_file: 0.9
  consecutive_required: 2
  min_attack_windows: 1
  cooldown_windows: 1
  smoothing: 0.1
  plausibility:
    ssdp_udp_1900_min_fraction: 0.1
    syn_min_syn_rate: 5.0
    icmp_min_rate: 5.0
    udp_min_rate: 5.0
    http_min_rate: 2.0
explainability:
  shap_background_size: 64
  top_features: 15
  attention: true
live:
  interface: any
  flush_seconds: 1.0
